"""
ComfyUI YX EasyUse Plugin
文件名格式化工具 & 游戏视频自动剪辑工具
"""

from .nodes.filename_formatter import NODE_CLASS_MAPPINGS as FILENAME_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as FILENAME_DISPLAY_MAPPINGS
from .nodes.game_video_auto_edit import NODE_CLASS_MAPPINGS as GAME_EDIT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as GAME_EDIT_DISPLAY_MAPPINGS

# 合并所有节点映射
NODE_CLASS_MAPPINGS = {**FILENAME_MAPPINGS, **GAME_EDIT_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**FILENAME_DISPLAY_MAPPINGS, **GAME_EDIT_DISPLAY_MAPPINGS}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]